### ISSUE TITLE
[GPL-V2/REQUEST] Please Release Nothing  Phone (2) Latest Android 13  Kernel Source

### ISSUE THREAD

**Issue by AbzRaider** [NothingOSS/android_kernel_msm-5.4_nothing_sm7325#10]

**Comment by itsHanibee** [comment]
mate i don't think the phone is out for sale yet, give em some time.

**Comment by AbzRaider** [comment]
> mate i don't think the phone is out for sale yet, give em some time.

yea 😂 ig with vayu they released source before launch just put this up so they will release asap

**Comment by Divyanshu-Modi** [comment]
Now that the device is launched @NothingOSS please release the sources for nothing phone 2

**Comment by arter97** [comment]
It's GPLv2, not v3, just so that everyone knows.

**Comment by AbzRaider** [comment]
> It's GPLv2, not v3, just so that everyone knows.

oh yea i'll correct the title , my bad

**Comment by NothingOSS** [comment]
https://github.com/NothingOSS/android_kernel_msm-5.10_nothing_sm8475 has been released.

**Comment by Divyanshu-Modi** [comment]
> https://github.com/NothingOSS/android_kernel_msm-5.10_nothing_sm8475 has been released.

Thx
