### ISSUE TITLE
MGLRU implementation crashes the phone when Magisk is used

### ISSUE THREAD

**Issue by LukeSkyD** [NothingOSS/android_kernel_msm-5.4_nothing_sm7325#7]
Nothing's implementation of the MGLRU kernel causes modified boot images to crash the phone.
Freezes and ramdumps are common if the device is rooted.
MGLRU implementations from other vendors do not cause such issue.

The possible culprits:
https://github.com/NothingOSS/android_kernel_msm-5.4_nothing_sm7325/commit/9278b64d56c7fe1c33768c3ecdface56201f785e
https://github.com/NothingOSS/android_kernel_msm-5.4_nothing_sm7325/commit/ed56a0636bd0e3a3def144daab31f020f7a44558

Magisk's issue where the problem was investigated but seems not to be on their part:
https://github.com/topjohnwu/Magisk/issues/6780

Disabling persist.sys.mglru_enable from system.prop solves the crashes but the underlying problem remains.

I can provide specific logs if asked.

**Comment by faekyu** [comment]
Any comment on this, @NothingOSS ?

For being a brand that (so far) seeks to attract users that appreciate flexibility and freedom, you'll get plenty of Magisk Rooted users which may no longer be able to use it as they previously had expected.

If you want to retain the loyalty of this part of your userbase, you'll need to take this seriously and with urgency. You're the self-proclaimed spiritual successor of OnePlus, claiming to want to make their wrongs right (to not break with the development support line that Carl Pei had intended when he co-founded OnePlus.. the brand that proceeded to drop developers stone cold and even implemented anti-developer features and deliberate, hard lockdowns) so if on the long term nothing gets done with this, it indicates it may have not been an accident and that there's a deviation from this line anyways. I'm not saying it will, we are gonna see.

**Comment by NothingOSS** [comment]
Thanks for reporting Nothing OS bug, this is being investigated for the next NOS update.
